### ISSUE TITLE
Add WiFi password

### ISSUE THREAD

**Issue by kristaboone** [WSUGreenArrow/gauss-vtm#1]
User's should have to enter a password to connect to the VTS. This comes standard with most UAV systems.

**Comment by zx96** [comment]
Should be easy enough to just make a simple Flask app that lets you change the AP name and password.

**Comment by zx96** [comment]
I kinda want to do this but there's no way in hell this is happening before documentation, and I have other stuff to do to finish up the semester. Might reopen if I'm free and bored.
